// 07_vue/05_vue_component_with_drf/todo-front/src/components/TodoList.vue
<template>
  <div class="todo-list">
    <div class="card" v-for="todo in todos" :key="todo.id">
      <div class="card-body">
        <span>{{ todo.title }}</span>
      </div>
    </div>
  </div>
</template>

<script>
  export default {
    name: 'TodoList',
    props: {
      todos: {
        type: Array,
        required: true,
      }
    }
  }
</script>

<style>

</style>

// 08_react/01_react_jsx/04_todo-app/src/components/TodoList.js
import React from 'react';
import TodoListItem from './TodoListItem';
import './TodoList.scss';

const TodoList = ({ todos, onRemove, onToggle }) => {
  return (
    <div className="TodoList">
      {todos.map(todo => (
        <TodoListItem
          todo={todo}
          key={todo.id}
          onRemove={onRemove}
          onToggle={onToggle}
        />
      ))}
    </div>
  );
};

export default TodoList;
